# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'function_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from testing_model import colorize_image


path = "Null"
text = "Null"
img1 = "b&w.jpg"
img2 = "original.jpg"

def process(path, img_type):
    result = colorize_image(path, img_type)
    return result



class Ui_FunctionWindow(object):

        
    def setupUi(self, FunctionWindow):
        FunctionWindow.setObjectName("FunctionWindow")
        FunctionWindow.resize(686, 516)
        self.centralwidget = QtWidgets.QWidget(FunctionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.original_img = QtWidgets.QLabel(self.frame_2)
        self.original_img.setText("")
        self.original_img.setPixmap(QtGui.QPixmap(img1))
        self.original_img.setObjectName("original_img")
        self.gridLayout_2.addWidget(self.original_img, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.result_img = QtWidgets.QLabel(self.frame_3)
        self.result_img.setMaximumSize(QtCore.QSize(1920, 1080))
        self.result_img.setText("")
        self.result_img.setPixmap(QtGui.QPixmap(img2))
        self.result_img.setObjectName("result_img")
        self.gridLayout.addWidget(self.result_img, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addWidget(self.frame_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 1, 0, 2, 2)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setMinimumSize(QtCore.QSize(500, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(1000, 200))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(self.frame_4)
        self.browse.setObjectName("browse")
        self.gridLayout_4.addWidget(self.browse, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_4)
        self.comboBox.setMinimumSize(QtCore.QSize(50, 22))
        self.comboBox.setMaximumSize(QtCore.QSize(110, 24))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_4.addWidget(self.comboBox, 1, 1, 1, 1)
        self.ProcessStart = QtWidgets.QPushButton(self.frame_4)
        self.ProcessStart.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ProcessStart.setStyleSheet("QPushButton{\n"
"   \n"
"    background-color: rgb(148, 148, 148);\n"
"\n"
"}")
        self.ProcessStart.setObjectName("ProcessStart")
        self.gridLayout_4.addWidget(self.ProcessStart, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        FunctionWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FunctionWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 686, 21))
        self.menubar.setObjectName("menubar")
        FunctionWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FunctionWindow)
        self.statusbar.setObjectName("statusbar")
        FunctionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FunctionWindow)
        QtCore.QMetaObject.connectSlotsByName(FunctionWindow)

    def retranslateUi(self, FunctionWindow):
        _translate = QtCore.QCoreApplication.translate
        FunctionWindow.setWindowTitle(_translate("FunctionWindow", "MainWindow"))
        self.label.setText(_translate("FunctionWindow", "Upload Image"))
        self.browse.setText(_translate("FunctionWindow", "Browse"))
        self.label_2.setText(_translate("FunctionWindow", "Image Type"))
        self.comboBox.setItemText(0, _translate("FunctionWindow", "Human Type"))
        self.comboBox.setItemText(1, _translate("FunctionWindow", "Nature Landscape"))
        self.comboBox.setItemText(2, _translate("FunctionWindow", "Other"))
        self.ProcessStart.setText(_translate("FunctionWindow", "Process Start"))
        self.browse.clicked.connect(self.browse_button_handler)
        self.ProcessStart.clicked.connect(self.processStart)
        
    def browse_button_handler(self):
        self.open_dialog_box()
   
    def open_dialog_box(self):
        filename = QFileDialog.getOpenFileName()
        global path
        path = filename[0]
        
    
    def processStart(self):
        global text
        text = str(self.comboBox.currentText())
        result = process(path, text)
        global img1, img2
        img1 = path
        img2 = result
        self.original_img.setPixmap(QtGui.QPixmap(img1))
        self.original_img.setObjectName("original_img")
        self.result_img.setPixmap(QtGui.QPixmap(img2))
        self.result_img.setObjectName("result_img")
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FunctionWindow = QtWidgets.QMainWindow()
    ui = Ui_FunctionWindow()
    ui.setupUi(FunctionWindow)
    FunctionWindow.show()
    sys.exit(app.exec_())






